import type { TypographyPreset } from './types';

export const TYPOGRAPHY_PRESETS: Record<string, TypographyPreset> = {
  'sam-hogan-drop': {
    title: 'Kinetic Drop',
    width: 1080,
    height: 1920,
    bgColor: '#0a0a0a',
    duration: 5.0,
    elements: [
      {
        id: 'element-1',
        type: 'text',
        text: 'KINETIC',
        fontFamily: 'JetBrains Mono',
        fontWeight: '900',
        fontSize: 260,
        letterSpacing: -10,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 0,
        x: 540,
        y: 700,
        animPreset: 'kinetic-drop',
        animDuration: 0.4,
        animStagger: 0.1,
        animShake: 40,
        animMotionBlur: 30,
        visible: true,
      },
      {
        id: 'element-2',
        type: 'text',
        text: 'DROP',
        fontFamily: 'JetBrains Mono',
        fontWeight: '900',
        fontSize: 340,
        letterSpacing: -15,
        fill: '#ef4444',
        stroke: '#000000',
        strokeWidth: 0,
        x: 540,
        y: 1000,
        animPreset: 'kinetic-drop',
        animDuration: 0.4,
        animStagger: 0.1,
        animShake: 70,
        animMotionBlur: 40,
        visible: true,
      }
    ]
  },
  'sam-hogan-slam': {
    title: 'Slam & Shake',
    width: 1080,
    height: 1920,
    bgColor: '#0a0a0a',
    duration: 5.0,
    elements: [
      {
        id: 'element-1',
        type: 'text',
        text: 'SAM',
        fontFamily: 'JetBrains Mono',
        fontWeight: '900',
        fontSize: 340,
        letterSpacing: -15,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 0,
        x: 540,
        y: 700,
        animPreset: 'sam-hogan',
        animDuration: 0.35,
        animStagger: 0.12,
        animShake: 50,
        animMotionBlur: 30,
        visible: true,
      },
      {
        id: 'element-2',
        type: 'text',
        text: 'HOGAN',
        fontFamily: 'JetBrains Mono',
        fontWeight: '900',
        fontSize: 340,
        letterSpacing: -15,
        fill: '#ef4444',
        stroke: '#000000',
        strokeWidth: 0,
        x: 540,
        y: 1000,
        animPreset: 'sam-hogan',
        animDuration: 0.35,
        animStagger: 0.12,
        animShake: 80,
        animMotionBlur: 30,
        visible: true,
      }
    ]
  },
  'ransom-collage': {
    title: 'Ransom Collage',
    width: 1080,
    height: 1080,
    bgColor: '#f4f4f5',
    duration: 5.0,
    elements: [
      {
        id: 'element-1',
        type: 'text',
        text: "MAGAZINE\nCOLLAGE",
        fontFamily: 'Caveat',
        fontWeight: '900',
        fontSize: 180,
        letterSpacing: 15,
        fill: '#000000',
        charStyles: [
            { fill: '#facc15', s: 1.1, r: -15 },
            { fill: '#ef4444', s: 0.9, r: 10 },
            { fill: '#3b82f6', s: 1.0, r: -5 },
            { fill: '#22c55e', s: 1.2, r: 15 },
            { fill: '#a855f7', s: 0.8, r: -20 },
            { fill: '#fb923c', s: 1.1, r: 5 },
            { fill: '#facc15', s: 1.0, r: 12 },
            { fill: '#ef4444', s: 0.9, r: -18 },
            
            { fill: '#3b82f6', s: 1.2, r: -5 },
            { fill: '#22c55e', s: 0.8, r: 20 },
            { fill: '#a855f7', s: 1.1, r: -10 },
            { fill: '#fb923c', s: 1.0, r: 15 },
            { fill: '#facc15', s: 0.9, r: -8 },
            { fill: '#ef4444', s: 1.2, r: 5 },
            { fill: '#3b82f6', s: 1.0, r: -12 }
        ],
        roughness: 3,
        innerShadowColor: '#000000',
        innerShadowBlur: 5,
        innerShadowX: 2,
        innerShadowY: 2,
        innerShadowOpacity: 30,
        shadowColor: '#000000',
        shadowBlur: 15,
        shadowOffsetX: 10,
        shadowOffsetY: 10,
        animPreset: 'pop-up',
        animDuration: 1.5,
        animStagger: 0.15,
        y: 540,
        x: 540,
        visible: true,
      }
    ]
  },
  'stop-motion': {
    title: 'Stop Motion',
    width: 1080,
    height: 1080,
    bgColor: '#e8dfd5',
    duration: 5.0,
    elements: [
      {
        id: 'element-1',
        type: 'text',
        text: "ORGANIC\nMOTION",
        fontFamily: 'Caveat',
        fontWeight: '700',
        fontSize: 180,
        fill: '#ef4444',
        stroke: '#000000',
        strokeWidth: 0,
        letterSpacing: 8,
        rotation: -2,
        roughness: 4,
        innerShadowColor: '#000000',
        innerShadowBlur: 4,
        innerShadowX: 2,
        innerShadowY: 2,
        innerShadowOpacity: 40,
        shadowColor: '#000000',
        shadowBlur: 12,
        shadowOffsetX: 8,
        shadowOffsetY: 8,
        y: 540,
        x: 540,
        animPreset: 'stop-motion',
        animDuration: 1.0,
        animStagger: 0,
        visible: true,
      }
    ]
  },
  'fireship-throw': {
    title: 'Fireship Bounce',
    width: 1280,
    height: 720,
    bgColor: '#18181b',
    duration: 5.0,
    elements: [
      {
        id: 'element-1',
        type: 'shape',
        shapeType: 'circle',
        w: 240,
        h: 240,
        fill: '#38bdf8',
        stroke: '#000000',
        strokeWidth: 0,
        x: 350,
        y: 300,
        shadowColor: '#000000',
        shadowOffsetX: 15,
        shadowOffsetY: 15,
        animPreset: 'pop-up',
        animDuration: 1.0,
        animStagger: 0.1,
        visible: true,
      },
      {
        id: 'element-2',
        type: 'text',
        text: 'BOUNCE',
        fontFamily: 'Rubik',
        fontWeight: '900',
        fontSize: 240,
        letterSpacing: -5,
        fill: '#ffffff',
        x: 740,
        y: 360,
        rotation: -2,
        shadowColor: '#000000',
        shadowOffsetX: 15,
        shadowOffsetY: 15,
        animPreset: 'throw',
        animDuration: 1.2,
        animStagger: 0.1,
        visible: true,
      }
    ]
  }
};
